/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package DataKeyManager;

import DataKeyManager.Controller.DataKeyController;
import org.junit.Test;
import static org.junit.Assert.*;

public class AppTest {
    @Test public void testAppHasAGreeting() {
        DataKeyController classUnderTest = new DataKeyController();
        assertNotNull("app should have a greeting", classUnderTest.Generate());
    }
}
